
import type { Product } from '@/types';

export const placeholderProducts: Product[] = [
  {
    id: '1',
    name: 'Classic T-Shirt',
    description: 'A comfortable and stylish classic t-shirt, perfect for everyday wear. Made from 100% premium cotton.',
    price: 29.99,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'tshirt fashion',
    category: 'Apparel',
  },
  {
    id: '2',
    name: 'Modern Smartphone',
    description: 'Latest generation smartphone with a stunning display, powerful processor, and an advanced camera system.',
    price: 699.99,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'smartphone technology',
    category: 'Electronics',
  },
  {
    id: '3',
    name: 'Wireless Headphones',
    description: 'Immersive sound experience with these noise-cancelling wireless headphones. Long battery life.',
    price: 199.99,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'headphones audio',
    category: 'Electronics',
  },
  {
    id: '4',
    name: 'Leather Wallet',
    description: 'Elegant and durable leather wallet with multiple card slots and a cash compartment.',
    price: 49.99,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'wallet accessory',
    category: 'Accessories',
  },
  {
    id: '5',
    name: 'Running Shoes',
    description: 'Lightweight and responsive running shoes designed for optimal performance and comfort.',
    price: 129.99,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'shoes sport',
    category: 'Footwear',
  },
  {
    id: '6',
    name: 'Coffee Maker',
    description: 'Start your day right with this easy-to-use coffee maker. Brews delicious coffee in minutes.',
    price: 79.99,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'coffee kitchen',
    category: 'Home Goods',
  },
   {
    id: '7',
    name: 'Yoga Mat',
    description: 'Premium non-slip yoga mat for your daily practice. Eco-friendly and durable material.',
    price: 39.99,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'yoga fitness',
    category: 'Sports',
  },
  {
    id: '8',
    name: 'Desk Lamp',
    description: 'Adjustable LED desk lamp with multiple brightness levels. Perfect for reading or working.',
    price: 59.99,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'lamp office',
    category: 'Office',
  },
];
